### ISSUE TITLE
Support for firefox?

### ISSUE THREAD

**Issue by tindtoast** [Kelvinouo/RoSaver#3]
Just wondering if there will be support for firefox since I am using it.

**Comment by Kelvinouo** [comment]
soon :TM:

**Comment by creature137** [comment]
Never.
![trolldespair-v0-q2lonbwiejx91-819685535](https://github.com/Kelvinouo/RoSaver/assets/161597780/454e395b-1eab-45e3-8cef-e967b6495752)
