### ISSUE TITLE
Not working ?

### ISSUE THREAD

**Issue by CaseDreamer** [Kelvinouo/RoSaver#4]
I tried the github version and unpacked it on chrome, and it said "Uncaught SyntaxError: Identifier 'rsaver_placeid' has already been declared"

also "Uncaught (in promise) Error: Frame with ID 0 was removed."

the extension one on chrome store is removed, any fix on these ?

cheers

**Comment by Kelvinouo** [comment]
nah it doesnt work since roblox patch the method of cashbacking via the api args. ill republie it when i found a new method of doing that.

**Comment by Kelvinouo** [comment]
closed - https://www.youtube.com/watch?v=HIwGqKlHfLc
