### ISSUE TITLE
Opens roblox uwp instead of web version

### ISSUE THREAD

**Issue by Kastlet** [Kelvinouo/RoSaver#5]
when i click save it opens a new tab where it asks for permission to open roblox, i click open, and instead of going with the web version it goes to the UWP app, which is annoying since i use that for a different account

**Comment by Kelvinouo** [comment]
you can update the protocol default programs in your os setting.

e.g. windows
[Open Default App Setting (microsoft support)](https://support.microsoft.com/en-us/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d) -> scroll down and click "Choose default apps by protocol"
![](https://i.imgur.com/HmbG5zh.png)

**Comment by Kastlet** [comment]
thank you that worked, but one thing i noticed, the extension doesn't seem to work on shirts? (5 robux), im supposed to get 2 robux however in my group whenever i buy a shirt, the pending robux remains the same (316) now i tried with a slightly more expensive item (20 robux) and i got 8 robux back, as it should, is there any reason as to why?

**Comment by Kelvinouo** [comment]
sorry for the late reply but, it seems to be lile a roblox end issues that to ignore low price of payback on 40% method
